# Generated by Django 6.0.3 on 2026-03-22 06:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', api.models.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
