# Generated by Django 6.0.3 on 2026-03-25 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_managers_material_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aviso_devolucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_aviso_devolucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_devuelta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_aviso_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENTREGADA', 'Entregada'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nombre', models.CharField(blank=True, max_length=200)),
                ('cantidad_pedida', models.IntegerField()),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de recibir'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad_llegada', models.IntegerField(blank=True, null=True)),
                ('cantidad_buena', models.IntegerField(blank=True, null=True)),
                ('cantidad_regular', models.IntegerField(blank=True, null=True)),
                ('cantidad_mala', models.IntegerField(blank=True, null=True)),
                ('comentario_malo', models.TextField(blank=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='api.material')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_recibidas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialProductoMalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nombre', models.CharField(max_length=200)),
                ('material_categoria', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_malos', to='api.compra')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_malos', to='api.material')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_malos', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_malos', to='api.solicitud')),
            ],
        ),
    ]
