# Generated by Django 6.0.3 on 2026-03-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solicitud_cantidad_buena_devuelta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialproductomalo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
