# Generated by Django 6.0.3 on 2026-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_historialproductomalo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad_buena',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_llegada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_mala',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_pedida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_regular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialproductomalo',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_min',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad_aviso_devolucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad_buena_devuelta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad_devuelta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad_mala_devuelta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
